datapull:
  api:
    s3_bucket_name:
  secretstore:
    vault:
      vault_url:
      static_secret_path_prefix:
      vault_nonce:
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  application:
    region:
  logger:
    s3:
      loggingfolder:
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    cloudwatch:
      groupName:
      streamName:
  email:
    smtp:
      emailaddress:
      smtpserveraddress:
    ses:
      email:
      access_key:
      secret_key: